"""add_model_key_column

Revision ID: 57a6d37c74da
Revises: aee9ee17c043
Create Date: 2025-12-04 18:45:34.293951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a6d37c74da'
down_revision: Union[str, Sequence[str], None] = 'aee9ee17c043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prediction_history', sa.Column('model_key', sa.String(), nullable=True))
    op.alter_column('prediction_history', 'threshold',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.5)'))
    op.alter_column('prediction_history', 'advice',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prediction_history', 'advice',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('prediction_history', 'threshold',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.5)'))
    op.drop_column('prediction_history', 'model_key')
    # ### end Alembic commands ###
